/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frs;

import java.awt.*;
import java.awt.event.*;
import java.awt.image.*;
import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.imageio.ImageIO;
import javax.swing.border.Border;

/**
 *
 * @author natha
 */
public class FRSGUI extends javax.swing.JFrame {
    
    public StringWriter sw = new StringWriter();
    public PrintWriter pw = new PrintWriter(sw);

    /**
     * Creates new form FRSGUI
     */
    public FRSGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new javax.swing.JPanel();
        SIDE_PANEL = new javax.swing.JPanel();
        LOGO_IMAGE = new javax.swing.JLabel();
        HOME_BUTTON = new javax.swing.JButton();
        SETTINGS_BUTTON = new javax.swing.JButton();
        MENGULANG_BUTTON = new javax.swing.JButton();
        BUKAN_JATAH_BUTTON = new javax.swing.JButton();
        CARD_TABS = new javax.swing.JPanel();
        HOME_PAGE = new javax.swing.JPanel();
        COPYRIGHT_LABEL_IN_HOME_PAGE = new javax.swing.JLabel();
        SELAMAT_DATANG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        APPLICATION_GUIDE_BUTTON = new javax.swing.JButton();
        EXCEL_GUIDE_BUTTON = new javax.swing.JButton();
        WELCOME = new javax.swing.JLabel();
        ABOUT_SCROLL = new javax.swing.JScrollPane();
        ABOUT_TEXT = new javax.swing.JTextArea();
        SETTINGS_PAGE = new javax.swing.JPanel();
        COPYRIGHT_LABEL_IN_SETTINGS_PAGE = new javax.swing.JLabel();
        PROSES_DATA_MENGULANG1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SETTINGS_SCROLL_MENU = new javax.swing.JScrollPane();
        SETTINGS_MENU = new javax.swing.JPanel();
        FORM_SETTINGS_PANEL = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ID_LABEL = new javax.swing.JLabel();
        ID_SPINNER = new javax.swing.JSpinner();
        COURSE_LABEL = new javax.swing.JLabel();
        COURSE_SPINNER = new javax.swing.JSpinner();
        WRITE_CLASS_NUMBER_LABEL = new javax.swing.JLabel();
        WRITE_CLASS_NUMBER_SPINNER = new javax.swing.JSpinner();
        NOTE_LABEL = new javax.swing.JLabel();
        NOTE_SPINNER = new javax.swing.JSpinner();
        DETAILS_SETTINGS_PANEL = new javax.swing.JPanel();
        COURSE_ID_LABEL = new javax.swing.JLabel();
        CLASS_LABEL = new javax.swing.JLabel();
        NUMBER_OF_STUDENTS_LABEL = new javax.swing.JLabel();
        COURSE_ID_SPINNER = new javax.swing.JSpinner();
        CLASS_SPINNER = new javax.swing.JSpinner();
        NUMBER_OF_STUDENTS_SPINNER = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        START_ROW_LABEL = new javax.swing.JLabel();
        START_ROW_SPINNER = new javax.swing.JSpinner();
        DEPARTMENT_LABEL = new javax.swing.JLabel();
        DEPARTMENT_SPINNER = new javax.swing.JSpinner();
        MISC_SETTINGS_PANEL = new javax.swing.JPanel();
        COURSE_LIMIT_LABEL = new javax.swing.JLabel();
        COURSE_LIMIT_SPINNER = new javax.swing.JSpinner();
        DELAY_LABEL = new javax.swing.JLabel();
        DELAY_SPINNER = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        SAVE_SETTINGS_BUTTON = new javax.swing.JButton();
        MENGULANG_PAGE = new javax.swing.JPanel();
        COPYRIGHT_LABEL_IN_MENGULANG_PAGE = new javax.swing.JLabel();
        PROSES_DATA_MENGULANG = new javax.swing.JLabel();
        INPUT_FILE_PANEL = new javax.swing.JPanel();
        FORM_INPUT_FILE_BROWSE_BUTTON = new javax.swing.JButton();
        DETAILS_INPUT_FILE_BROWSE_BUTTON = new javax.swing.JButton();
        FORM_INPUT_LABEL = new javax.swing.JLabel();
        DETAILS_INPUT_LABEL = new javax.swing.JLabel();
        FORM_INPUT_PATH_FIELD = new javax.swing.JTextField();
        DETAILS_INPUT_PATH_FIELD = new javax.swing.JTextField();
        SUBMIT_BUTTON = new javax.swing.JButton();
        LOG_SCROLL_PANE = new javax.swing.JScrollPane();
        LOG_TEXT_AREA = new javax.swing.JTextArea();
        BUKAN_JATAH_PAGE = new javax.swing.JPanel();
        COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE = new javax.swing.JLabel();
        PROSES_DATA_BUKAN_JATAH = new javax.swing.JLabel();
        INPUT_FILE_PANEL2 = new javax.swing.JPanel();
        FORM_INPUT_FILE_BROWSE_BUTTON2 = new javax.swing.JButton();
        DETAILS_INPUT_FILE_BROWSE_BUTTON2 = new javax.swing.JButton();
        FORM_INPUT_LABEL2 = new javax.swing.JLabel();
        DETAILS_INPUT_LABEL2 = new javax.swing.JLabel();
        FORM_INPUT_PATH_FIELD2 = new javax.swing.JTextField();
        DETAILS_INPUT_PATH_FIELD2 = new javax.swing.JTextField();
        SUBMIT_BUTTON1 = new javax.swing.JButton();
        LOG_SCROLL_PANE1 = new javax.swing.JScrollPane();
        LOG_TEXT_AREA1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi FRS SKPB");
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));

        SIDE_PANEL.setBackground(new java.awt.Color(255, 255, 255));
        SIDE_PANEL.setPreferredSize(new java.awt.Dimension(300, 700));

        LOGO_IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frs/images/Logo SKPB-biru.png"))); // NOI18N
        LOGO_IMAGE.setToolTipText("Tempat KP terbaik");
        LOGO_IMAGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGO_IMAGEMouseClicked(evt);
            }
        });

        HOME_BUTTON.setBackground(new java.awt.Color(9, 121, 191));
        HOME_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 28)); // NOI18N
        HOME_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        HOME_BUTTON.setText("Home");
        HOME_BUTTON.setToolTipText("Kembali ke halaman utama");
        HOME_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HOME_BUTTON.setPreferredSize(new java.awt.Dimension(200, 70));
        HOME_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOME_BUTTONActionPerformed(evt);
            }
        });

        SETTINGS_BUTTON.setBackground(new java.awt.Color(9, 121, 191));
        SETTINGS_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24)); // NOI18N
        SETTINGS_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        SETTINGS_BUTTON.setText("Settings");
        SETTINGS_BUTTON.setToolTipText("Sesuaikan program dengan pengaturan kustom");
        SETTINGS_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SETTINGS_BUTTON.setPreferredSize(new java.awt.Dimension(200, 70));
        SETTINGS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SETTINGS_BUTTONActionPerformed(evt);
            }
        });

        MENGULANG_BUTTON.setBackground(new java.awt.Color(9, 121, 191));
        MENGULANG_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24)); // NOI18N
        MENGULANG_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        MENGULANG_BUTTON.setText("Mengulang");
        MENGULANG_BUTTON.setToolTipText("Mulai proses mahasiswa yang mengulang");
        MENGULANG_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MENGULANG_BUTTON.setPreferredSize(new java.awt.Dimension(200, 70));
        MENGULANG_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENGULANG_BUTTONActionPerformed(evt);
            }
        });

        BUKAN_JATAH_BUTTON.setBackground(new java.awt.Color(9, 121, 191));
        BUKAN_JATAH_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24)); // NOI18N
        BUKAN_JATAH_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        BUKAN_JATAH_BUTTON.setText("Bukan Jatah");
        BUKAN_JATAH_BUTTON.setToolTipText("Mulai proses mahasiswa yang bukan jatah");
        BUKAN_JATAH_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BUKAN_JATAH_BUTTON.setPreferredSize(new java.awt.Dimension(200, 70));
        BUKAN_JATAH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUKAN_JATAH_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SIDE_PANELLayout = new javax.swing.GroupLayout(SIDE_PANEL);
        SIDE_PANEL.setLayout(SIDE_PANELLayout);
        SIDE_PANELLayout.setHorizontalGroup(
            SIDE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIDE_PANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGO_IMAGE)
                .addGap(50, 50, 50))
            .addGroup(SIDE_PANELLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(SIDE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SETTINGS_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUKAN_JATAH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MENGULANG_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HOME_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        SIDE_PANELLayout.setVerticalGroup(
            SIDE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIDE_PANELLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(LOGO_IMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(HOME_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SETTINGS_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(MENGULANG_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUKAN_JATAH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        CARD_TABS.setPreferredSize(new java.awt.Dimension(750, 700));
        CARD_TABS.setLayout(new java.awt.CardLayout());

        HOME_PAGE.setBackground(new java.awt.Color(255, 255, 255));

        COPYRIGHT_LABEL_IN_HOME_PAGE.setBackground(new java.awt.Color(255, 255, 255));
        COPYRIGHT_LABEL_IN_HOME_PAGE.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        COPYRIGHT_LABEL_IN_HOME_PAGE.setForeground(new java.awt.Color(102, 102, 102));
        COPYRIGHT_LABEL_IN_HOME_PAGE.setText("© 2024, Nathaniel Takeshi & Yesaya Ananda with SKPB ITS");

        SELAMAT_DATANG.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 48)); // NOI18N
        SELAMAT_DATANG.setForeground(new java.awt.Color(0, 0, 0));
        SELAMAT_DATANG.setText("Tentang Aplikasi");

        jLabel1.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Pertama kali menggunakan?");

        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Silakan simak panduan berikut!");

        jLabel3.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Sudah memahami? Tekan tombol pada panel sebelah kiri untuk memulai!");

        APPLICATION_GUIDE_BUTTON.setBackground(new java.awt.Color(0, 85, 170));
        APPLICATION_GUIDE_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        APPLICATION_GUIDE_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        APPLICATION_GUIDE_BUTTON.setText("Aplikasi");
        APPLICATION_GUIDE_BUTTON.setToolTipText("Klik untuk panduan penggunaan aplikasi");
        APPLICATION_GUIDE_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        APPLICATION_GUIDE_BUTTON.setPreferredSize(new java.awt.Dimension(150, 40));
        APPLICATION_GUIDE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APPLICATION_GUIDE_BUTTONActionPerformed(evt);
            }
        });

        EXCEL_GUIDE_BUTTON.setBackground(new java.awt.Color(0, 85, 170));
        EXCEL_GUIDE_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        EXCEL_GUIDE_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        EXCEL_GUIDE_BUTTON.setText("Excel");
        EXCEL_GUIDE_BUTTON.setToolTipText("Klik untuk panduan penggunaan format Excel");
        EXCEL_GUIDE_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EXCEL_GUIDE_BUTTON.setPreferredSize(new java.awt.Dimension(150, 40));
        EXCEL_GUIDE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCEL_GUIDE_BUTTONActionPerformed(evt);
            }
        });

        WELCOME.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 48)); // NOI18N
        WELCOME.setForeground(new java.awt.Color(0, 0, 0));
        WELCOME.setText("Selamat Datang!");

        ABOUT_SCROLL.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ABOUT_TEXT.setColumns(20);
        ABOUT_TEXT.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 16)); // NOI18N
        ABOUT_TEXT.setLineWrap(true);
        ABOUT_TEXT.setRows(5);
        ABOUT_TEXT.setText("Aplikasi ini didesain untuk menangani proses memasukkan kelas mahasiswa bagi yang mengulang atau mengambil mata kuliah bukan jatah. Sekaligus, sebagai hasil kerja keras selama periode kerja praktek di SKPB.\n\nDi sisi lain, aplikasi ini adalah bentuk rasa terima kasih kami selama kerja praktik di SKPB yang dilayani secara luar biasa tanpa kekurangan sesuatu apapun.");
        ABOUT_TEXT.setEditable(false);
        ABOUT_TEXT.setWrapStyleWord(true);
        ABOUT_TEXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ABOUT_SCROLL.setViewportView(ABOUT_TEXT);

        javax.swing.GroupLayout HOME_PAGELayout = new javax.swing.GroupLayout(HOME_PAGE);
        HOME_PAGE.setLayout(HOME_PAGELayout);
        HOME_PAGELayout.setHorizontalGroup(
            HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOME_PAGELayout.createSequentialGroup()
                .addGroup(HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HOME_PAGELayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(COPYRIGHT_LABEL_IN_HOME_PAGE))
                    .addGroup(HOME_PAGELayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HOME_PAGELayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(HOME_PAGELayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(APPLICATION_GUIDE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXCEL_GUIDE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(HOME_PAGELayout.createSequentialGroup()
                .addGroup(HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HOME_PAGELayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(SELAMAT_DATANG))
                    .addGroup(HOME_PAGELayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(WELCOME))
                    .addGroup(HOME_PAGELayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(ABOUT_SCROLL, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        HOME_PAGELayout.setVerticalGroup(
            HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HOME_PAGELayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(WELCOME)
                .addGap(40, 40, 40)
                .addGroup(HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(HOME_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APPLICATION_GUIDE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXCEL_GUIDE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(70, 70, 70)
                .addComponent(SELAMAT_DATANG)
                .addGap(40, 40, 40)
                .addComponent(ABOUT_SCROLL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(COPYRIGHT_LABEL_IN_HOME_PAGE)
                .addContainerGap())
        );

        CARD_TABS.add(HOME_PAGE, "HOME_PAGE");

        SETTINGS_PAGE.setBackground(new java.awt.Color(255, 255, 255));

        COPYRIGHT_LABEL_IN_SETTINGS_PAGE.setBackground(new java.awt.Color(255, 255, 255));
        COPYRIGHT_LABEL_IN_SETTINGS_PAGE.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        COPYRIGHT_LABEL_IN_SETTINGS_PAGE.setForeground(new java.awt.Color(102, 102, 102));
        COPYRIGHT_LABEL_IN_SETTINGS_PAGE.setText("© 2024, Nathaniel Takeshi & Yesaya Ananda with SKPB ITS");

        PROSES_DATA_MENGULANG1.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 48)); // NOI18N
        PROSES_DATA_MENGULANG1.setForeground(new java.awt.Color(0, 0, 0));
        PROSES_DATA_MENGULANG1.setText("Pengaturan");

        jLabel4.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Beberapa kustomisasi untuk menyesuaikan kebutuhan penjalanan program.");

        SETTINGS_SCROLL_MENU.setBackground(new java.awt.Color(255, 255, 255));
        SETTINGS_SCROLL_MENU.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        SETTINGS_SCROLL_MENU.setToolTipText("Gulir ke bawah ");

        SETTINGS_MENU.setBackground(new java.awt.Color(255, 255, 255));

        FORM_SETTINGS_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kolom Excel G-Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24))); // NOI18N

        jLabel10.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel10.setText("Atur posisi kolom Excel G-Form.");

        ID_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        ID_LABEL.setText("NRP");

        ID_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        ID_SPINNER.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));
        ID_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        ID_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        COURSE_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        COURSE_LABEL.setText("Kode Mata Kuliah");

        COURSE_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        COURSE_SPINNER.setModel(new javax.swing.SpinnerNumberModel(5, 1, null, 1));
        COURSE_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        COURSE_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        WRITE_CLASS_NUMBER_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        WRITE_CLASS_NUMBER_LABEL.setText("Tulis Kelas");

        WRITE_CLASS_NUMBER_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        WRITE_CLASS_NUMBER_SPINNER.setModel(new javax.swing.SpinnerNumberModel(6, 1, null, 1));
        WRITE_CLASS_NUMBER_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        WRITE_CLASS_NUMBER_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        NOTE_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        NOTE_LABEL.setText("Kasih Catatan");

        NOTE_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        NOTE_SPINNER.setModel(new javax.swing.SpinnerNumberModel(8, 1, null, 1));
        NOTE_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        NOTE_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        javax.swing.GroupLayout FORM_SETTINGS_PANELLayout = new javax.swing.GroupLayout(FORM_SETTINGS_PANEL);
        FORM_SETTINGS_PANEL.setLayout(FORM_SETTINGS_PANELLayout);
        FORM_SETTINGS_PANELLayout.setHorizontalGroup(
            FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                        .addGroup(FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(ID_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ID_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(COURSE_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                .addComponent(COURSE_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(WRITE_CLASS_NUMBER_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                .addComponent(WRITE_CLASS_NUMBER_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(NOTE_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(NOTE_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
        );
        FORM_SETTINGS_PANELLayout.setVerticalGroup(
            FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FORM_SETTINGS_PANELLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addGroup(FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_LABEL)
                    .addComponent(ID_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COURSE_LABEL)
                    .addComponent(COURSE_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WRITE_CLASS_NUMBER_LABEL)
                    .addComponent(WRITE_CLASS_NUMBER_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(FORM_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOTE_LABEL)
                    .addComponent(NOTE_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        DETAILS_SETTINGS_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kolom Detail Kelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24))); // NOI18N

        COURSE_ID_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        COURSE_ID_LABEL.setText("Kode Mata Kuliah");

        CLASS_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        CLASS_LABEL.setText("Kelas");

        NUMBER_OF_STUDENTS_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        NUMBER_OF_STUDENTS_LABEL.setText("Banyak Mahasiswa");

        COURSE_ID_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        COURSE_ID_SPINNER.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        COURSE_ID_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        COURSE_ID_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        CLASS_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        CLASS_SPINNER.setModel(new javax.swing.SpinnerNumberModel(7, 1, null, 1));
        CLASS_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        CLASS_SPINNER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLASS_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        NUMBER_OF_STUDENTS_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        NUMBER_OF_STUDENTS_SPINNER.setModel(new javax.swing.SpinnerNumberModel(8, 1, null, 1));
        NUMBER_OF_STUDENTS_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        NUMBER_OF_STUDENTS_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        jLabel11.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel11.setText("Atur posisi kolom Detail Kelas.");

        START_ROW_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        START_ROW_LABEL.setText("Baris mulai");

        START_ROW_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        START_ROW_SPINNER.setModel(new javax.swing.SpinnerNumberModel(5, 1, null, 1));
        START_ROW_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        START_ROW_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        DEPARTMENT_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        DEPARTMENT_LABEL.setText("Departemen");

        DEPARTMENT_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        DEPARTMENT_SPINNER.setModel(new javax.swing.SpinnerNumberModel(9, 1, null, 1));
        DEPARTMENT_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        DEPARTMENT_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        javax.swing.GroupLayout DETAILS_SETTINGS_PANELLayout = new javax.swing.GroupLayout(DETAILS_SETTINGS_PANEL);
        DETAILS_SETTINGS_PANEL.setLayout(DETAILS_SETTINGS_PANELLayout);
        DETAILS_SETTINGS_PANELLayout.setHorizontalGroup(
            DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                        .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(COURSE_ID_LABEL)
                                    .addComponent(NUMBER_OF_STUDENTS_LABEL)
                                    .addComponent(CLASS_LABEL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(COURSE_ID_SPINNER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CLASS_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NUMBER_OF_STUDENTS_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(START_ROW_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(START_ROW_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(DEPARTMENT_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addComponent(DEPARTMENT_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
        );
        DETAILS_SETTINGS_PANELLayout.setVerticalGroup(
            DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DETAILS_SETTINGS_PANELLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(START_ROW_LABEL)
                    .addComponent(START_ROW_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COURSE_ID_LABEL)
                    .addComponent(COURSE_ID_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLASS_LABEL)
                    .addComponent(CLASS_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUMBER_OF_STUDENTS_LABEL)
                    .addComponent(NUMBER_OF_STUDENTS_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DETAILS_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DEPARTMENT_LABEL)
                    .addComponent(DEPARTMENT_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        MISC_SETTINGS_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pengaturan Lainnya", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24))); // NOI18N

        COURSE_LIMIT_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        COURSE_LIMIT_LABEL.setText("Banyak Mata Kuliah");

        COURSE_LIMIT_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        COURSE_LIMIT_SPINNER.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));
        COURSE_LIMIT_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        COURSE_LIMIT_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        DELAY_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        DELAY_LABEL.setText("Jeda antar prosedur (detik)");

        DELAY_SPINNER.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        DELAY_SPINNER.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        DELAY_SPINNER.setToolTipText("Ketik atau klik tombol untuk mengubah nilai");
        DELAY_SPINNER.setMinimumSize(new java.awt.Dimension(70, 22));

        jLabel14.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 18)); // NOI18N
        jLabel14.setText("Hanya untuk kebutuhan kustom.");

        javax.swing.GroupLayout MISC_SETTINGS_PANELLayout = new javax.swing.GroupLayout(MISC_SETTINGS_PANEL);
        MISC_SETTINGS_PANEL.setLayout(MISC_SETTINGS_PANELLayout);
        MISC_SETTINGS_PANELLayout.setHorizontalGroup(
            MISC_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MISC_SETTINGS_PANELLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(MISC_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MISC_SETTINGS_PANELLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MISC_SETTINGS_PANELLayout.createSequentialGroup()
                        .addGroup(MISC_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MISC_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(COURSE_LIMIT_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(COURSE_LIMIT_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MISC_SETTINGS_PANELLayout.createSequentialGroup()
                                .addComponent(DELAY_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DELAY_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
        );
        MISC_SETTINGS_PANELLayout.setVerticalGroup(
            MISC_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MISC_SETTINGS_PANELLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(MISC_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COURSE_LIMIT_LABEL)
                    .addComponent(COURSE_LIMIT_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MISC_SETTINGS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DELAY_LABEL)
                    .addComponent(DELAY_SPINNER, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SETTINGS_MENULayout = new javax.swing.GroupLayout(SETTINGS_MENU);
        SETTINGS_MENU.setLayout(SETTINGS_MENULayout);
        SETTINGS_MENULayout.setHorizontalGroup(
            SETTINGS_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETTINGS_MENULayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(SETTINGS_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FORM_SETTINGS_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DETAILS_SETTINGS_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MISC_SETTINGS_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        SETTINGS_MENULayout.setVerticalGroup(
            SETTINGS_MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SETTINGS_MENULayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(FORM_SETTINGS_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(DETAILS_SETTINGS_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(MISC_SETTINGS_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        SETTINGS_SCROLL_MENU.setViewportView(SETTINGS_MENU);

        SAVE_SETTINGS_BUTTON.setBackground(new java.awt.Color(0, 85, 170));
        SAVE_SETTINGS_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 20)); // NOI18N
        SAVE_SETTINGS_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        SAVE_SETTINGS_BUTTON.setText("Save");
        SAVE_SETTINGS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_SETTINGS_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SETTINGS_PAGELayout = new javax.swing.GroupLayout(SETTINGS_PAGE);
        SETTINGS_PAGE.setLayout(SETTINGS_PAGELayout);
        SETTINGS_PAGELayout.setHorizontalGroup(
            SETTINGS_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETTINGS_PAGELayout.createSequentialGroup()
                .addGroup(SETTINGS_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SETTINGS_PAGELayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(COPYRIGHT_LABEL_IN_SETTINGS_PAGE))
                    .addGroup(SETTINGS_PAGELayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(SETTINGS_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(PROSES_DATA_MENGULANG1)
                            .addComponent(SETTINGS_SCROLL_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SETTINGS_PAGELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SAVE_SETTINGS_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        SETTINGS_PAGELayout.setVerticalGroup(
            SETTINGS_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SETTINGS_PAGELayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(PROSES_DATA_MENGULANG1)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(SETTINGS_SCROLL_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(SAVE_SETTINGS_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(COPYRIGHT_LABEL_IN_SETTINGS_PAGE)
                .addContainerGap())
        );

        CARD_TABS.add(SETTINGS_PAGE, "card5");

        MENGULANG_PAGE.setBackground(new java.awt.Color(255, 255, 255));

        COPYRIGHT_LABEL_IN_MENGULANG_PAGE.setBackground(new java.awt.Color(255, 255, 255));
        COPYRIGHT_LABEL_IN_MENGULANG_PAGE.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        COPYRIGHT_LABEL_IN_MENGULANG_PAGE.setForeground(new java.awt.Color(102, 102, 102));
        COPYRIGHT_LABEL_IN_MENGULANG_PAGE.setText("© 2024, Nathaniel Takeshi & Yesaya Ananda with SKPB ITS");

        PROSES_DATA_MENGULANG.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 48)); // NOI18N
        PROSES_DATA_MENGULANG.setForeground(new java.awt.Color(0, 0, 0));
        PROSES_DATA_MENGULANG.setText("Proses Data Mengulang");

        INPUT_FILE_PANEL.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_FILE_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input File", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        INPUT_FILE_PANEL.setToolTipText("Masukkan file-file yang dibutuhkan di sini");

        FORM_INPUT_FILE_BROWSE_BUTTON.setBackground(new java.awt.Color(0, 116, 185));
        FORM_INPUT_FILE_BROWSE_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        FORM_INPUT_FILE_BROWSE_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        FORM_INPUT_FILE_BROWSE_BUTTON.setText("Cari");
        FORM_INPUT_FILE_BROWSE_BUTTON.setToolTipText("Atau, klik untuk mencari file secara langsung");
        FORM_INPUT_FILE_BROWSE_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FORM_INPUT_FILE_BROWSE_BUTTON.setPreferredSize(new java.awt.Dimension(75, 30));
        FORM_INPUT_FILE_BROWSE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORM_INPUT_FILE_BROWSE_BUTTONActionPerformed(evt);
            }
        });

        DETAILS_INPUT_FILE_BROWSE_BUTTON.setBackground(new java.awt.Color(0, 116, 185));
        DETAILS_INPUT_FILE_BROWSE_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        DETAILS_INPUT_FILE_BROWSE_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        DETAILS_INPUT_FILE_BROWSE_BUTTON.setText("Cari");
        DETAILS_INPUT_FILE_BROWSE_BUTTON.setToolTipText("Atau, klik untuk mencari file secara langsung");
        DETAILS_INPUT_FILE_BROWSE_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DETAILS_INPUT_FILE_BROWSE_BUTTON.setPreferredSize(new java.awt.Dimension(75, 30));
        DETAILS_INPUT_FILE_BROWSE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETAILS_INPUT_FILE_BROWSE_BUTTONActionPerformed(evt);
            }
        });

        FORM_INPUT_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        FORM_INPUT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        FORM_INPUT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FORM_INPUT_LABEL.setText("File dari G-Form");
        FORM_INPUT_LABEL.setToolTipText("File Excel dari G-Form");

        DETAILS_INPUT_LABEL.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        DETAILS_INPUT_LABEL.setForeground(new java.awt.Color(0, 0, 0));
        DETAILS_INPUT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DETAILS_INPUT_LABEL.setText("Excel Detail Kelas");
        DETAILS_INPUT_LABEL.setToolTipText("File Excel berisikan data kelas");

        FORM_INPUT_PATH_FIELD.setBackground(new java.awt.Color(255, 255, 255));
        FORM_INPUT_PATH_FIELD.setForeground(new java.awt.Color(204, 204, 204));
        FORM_INPUT_PATH_FIELD.setText("Masukkan path file...");
        FORM_INPUT_PATH_FIELD.setToolTipText("Masukkan path file di sini");
        FORM_INPUT_PATH_FIELD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FORM_INPUT_PATH_FIELDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FORM_INPUT_PATH_FIELDFocusLost(evt);
            }
        });

        DETAILS_INPUT_PATH_FIELD.setBackground(new java.awt.Color(255, 255, 255));
        DETAILS_INPUT_PATH_FIELD.setForeground(new java.awt.Color(204, 204, 204));
        DETAILS_INPUT_PATH_FIELD.setText("Masukkan path file...");
        DETAILS_INPUT_PATH_FIELD.setToolTipText("Masukkan path file di sini");
        DETAILS_INPUT_PATH_FIELD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DETAILS_INPUT_PATH_FIELDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DETAILS_INPUT_PATH_FIELDFocusLost(evt);
            }
        });

        javax.swing.GroupLayout INPUT_FILE_PANELLayout = new javax.swing.GroupLayout(INPUT_FILE_PANEL);
        INPUT_FILE_PANEL.setLayout(INPUT_FILE_PANELLayout);
        INPUT_FILE_PANELLayout.setHorizontalGroup(
            INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INPUT_FILE_PANELLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DETAILS_INPUT_LABEL)
                    .addComponent(FORM_INPUT_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FORM_INPUT_PATH_FIELD)
                    .addComponent(DETAILS_INPUT_PATH_FIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DETAILS_INPUT_FILE_BROWSE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FORM_INPUT_FILE_BROWSE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        INPUT_FILE_PANELLayout.setVerticalGroup(
            INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_FILE_PANELLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FORM_INPUT_FILE_BROWSE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FORM_INPUT_LABEL)
                    .addComponent(FORM_INPUT_PATH_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(INPUT_FILE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DETAILS_INPUT_FILE_BROWSE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DETAILS_INPUT_LABEL)
                    .addComponent(DETAILS_INPUT_PATH_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        SUBMIT_BUTTON.setBackground(new java.awt.Color(0, 85, 170));
        SUBMIT_BUTTON.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 20)); // NOI18N
        SUBMIT_BUTTON.setForeground(new java.awt.Color(255, 255, 255));
        SUBMIT_BUTTON.setText("Submit");
        SUBMIT_BUTTON.setToolTipText("Klik tombol ini untuk menjalankan program");
        SUBMIT_BUTTON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUBMIT_BUTTON.setPreferredSize(new java.awt.Dimension(120, 50));
        SUBMIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMIT_BUTTONActionPerformed(evt);
            }
        });

        LOG_SCROLL_PANE.setToolTipText("Log program akan muncul di sini");

        LOG_TEXT_AREA.setBackground(new java.awt.Color(255, 255, 255));
        LOG_TEXT_AREA.setEditable(true);
        LOG_TEXT_AREA.setColumns(20);
        LOG_TEXT_AREA.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        LOG_TEXT_AREA.setForeground(new java.awt.Color(0, 0, 0));
        LOG_TEXT_AREA.setRows(5);
        LOG_TEXT_AREA.setToolTipText("Log program akan muncul di sini");
        LOG_TEXT_AREA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Penjalanan Program", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        LOG_SCROLL_PANE.setViewportView(LOG_TEXT_AREA);

        javax.swing.GroupLayout MENGULANG_PAGELayout = new javax.swing.GroupLayout(MENGULANG_PAGE);
        MENGULANG_PAGE.setLayout(MENGULANG_PAGELayout);
        MENGULANG_PAGELayout.setHorizontalGroup(
            MENGULANG_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENGULANG_PAGELayout.createSequentialGroup()
                .addGroup(MENGULANG_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENGULANG_PAGELayout.createSequentialGroup()
                        .addGroup(MENGULANG_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MENGULANG_PAGELayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(MENGULANG_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PROSES_DATA_MENGULANG)
                                    .addComponent(INPUT_FILE_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LOG_SCROLL_PANE)))
                            .addGroup(MENGULANG_PAGELayout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(SUBMIT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENGULANG_PAGELayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(COPYRIGHT_LABEL_IN_MENGULANG_PAGE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MENGULANG_PAGELayout.setVerticalGroup(
            MENGULANG_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENGULANG_PAGELayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(PROSES_DATA_MENGULANG)
                .addGap(30, 30, 30)
                .addComponent(INPUT_FILE_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(SUBMIT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LOG_SCROLL_PANE, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(COPYRIGHT_LABEL_IN_MENGULANG_PAGE)
                .addContainerGap())
        );

        CARD_TABS.add(MENGULANG_PAGE, "card3");

        BUKAN_JATAH_PAGE.setBackground(new java.awt.Color(255, 255, 255));

        COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE.setBackground(new java.awt.Color(255, 255, 255));
        COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE.setForeground(new java.awt.Color(102, 102, 102));
        COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE.setText("© 2024, Nathaniel Takeshi & Yesaya Ananda with SKPB ITS");

        PROSES_DATA_BUKAN_JATAH.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 48)); // NOI18N
        PROSES_DATA_BUKAN_JATAH.setForeground(new java.awt.Color(0, 0, 0));
        PROSES_DATA_BUKAN_JATAH.setText("Proses Data Bukan Jatah");

        INPUT_FILE_PANEL2.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_FILE_PANEL2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input File", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        INPUT_FILE_PANEL2.setToolTipText("Masukkan file-file yang dibutuhkan di sini");

        FORM_INPUT_FILE_BROWSE_BUTTON2.setBackground(new java.awt.Color(0, 116, 185));
        FORM_INPUT_FILE_BROWSE_BUTTON2.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        FORM_INPUT_FILE_BROWSE_BUTTON2.setForeground(new java.awt.Color(255, 255, 255));
        FORM_INPUT_FILE_BROWSE_BUTTON2.setText("Cari");
        FORM_INPUT_FILE_BROWSE_BUTTON2.setToolTipText("Atau, klik untuk mencari file secara langsung");
        FORM_INPUT_FILE_BROWSE_BUTTON2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FORM_INPUT_FILE_BROWSE_BUTTON2.setPreferredSize(new java.awt.Dimension(75, 30));
        FORM_INPUT_FILE_BROWSE_BUTTON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FORM_INPUT_FILE_BROWSE_BUTTON2ActionPerformed(evt);
            }
        });

        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setBackground(new java.awt.Color(0, 116, 185));
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setForeground(new java.awt.Color(255, 255, 255));
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setText("Cari");
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setToolTipText("Atau, klik untuk mencari file secara langsung");
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.setPreferredSize(new java.awt.Dimension(75, 30));
        DETAILS_INPUT_FILE_BROWSE_BUTTON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETAILS_INPUT_FILE_BROWSE_BUTTON2ActionPerformed(evt);
            }
        });

        FORM_INPUT_LABEL2.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        FORM_INPUT_LABEL2.setForeground(new java.awt.Color(0, 0, 0));
        FORM_INPUT_LABEL2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FORM_INPUT_LABEL2.setText("File dari G-Form");

        DETAILS_INPUT_LABEL2.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 18)); // NOI18N
        DETAILS_INPUT_LABEL2.setForeground(new java.awt.Color(0, 0, 0));
        DETAILS_INPUT_LABEL2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DETAILS_INPUT_LABEL2.setText("Excel Detail Kelas");

        FORM_INPUT_PATH_FIELD2.setBackground(new java.awt.Color(255, 255, 255));
        FORM_INPUT_PATH_FIELD2.setForeground(new java.awt.Color(204, 204, 204));
        FORM_INPUT_PATH_FIELD2.setText("Masukkan path file...");
        FORM_INPUT_PATH_FIELD2.setToolTipText("Masukkan path file di sini");
        FORM_INPUT_PATH_FIELD2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FORM_INPUT_PATH_FIELD2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FORM_INPUT_PATH_FIELD2FocusLost(evt);
            }
        });

        DETAILS_INPUT_PATH_FIELD2.setBackground(new java.awt.Color(255, 255, 255));
        DETAILS_INPUT_PATH_FIELD2.setForeground(new java.awt.Color(204, 204, 204));
        DETAILS_INPUT_PATH_FIELD2.setText("Masukkan path file...");
        DETAILS_INPUT_PATH_FIELD2.setToolTipText("Masukkan path file di sini");
        DETAILS_INPUT_PATH_FIELD2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DETAILS_INPUT_PATH_FIELD2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DETAILS_INPUT_PATH_FIELD2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout INPUT_FILE_PANEL2Layout = new javax.swing.GroupLayout(INPUT_FILE_PANEL2);
        INPUT_FILE_PANEL2.setLayout(INPUT_FILE_PANEL2Layout);
        INPUT_FILE_PANEL2Layout.setHorizontalGroup(
            INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INPUT_FILE_PANEL2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DETAILS_INPUT_LABEL2)
                    .addComponent(FORM_INPUT_LABEL2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FORM_INPUT_PATH_FIELD2)
                    .addComponent(DETAILS_INPUT_PATH_FIELD2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DETAILS_INPUT_FILE_BROWSE_BUTTON2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FORM_INPUT_FILE_BROWSE_BUTTON2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        INPUT_FILE_PANEL2Layout.setVerticalGroup(
            INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INPUT_FILE_PANEL2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FORM_INPUT_FILE_BROWSE_BUTTON2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FORM_INPUT_LABEL2)
                    .addComponent(FORM_INPUT_PATH_FIELD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(INPUT_FILE_PANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DETAILS_INPUT_FILE_BROWSE_BUTTON2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DETAILS_INPUT_LABEL2)
                    .addComponent(DETAILS_INPUT_PATH_FIELD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        SUBMIT_BUTTON1.setBackground(new java.awt.Color(0, 85, 170));
        SUBMIT_BUTTON1.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 20)); // NOI18N
        SUBMIT_BUTTON1.setForeground(new java.awt.Color(255, 255, 255));
        SUBMIT_BUTTON1.setText("Submit");
        SUBMIT_BUTTON1.setToolTipText("Klik tombol ini untuk menjalankan program");
        SUBMIT_BUTTON1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUBMIT_BUTTON1.setPreferredSize(new java.awt.Dimension(120, 50));
        SUBMIT_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMIT_BUTTON1ActionPerformed(evt);
            }
        });

        LOG_TEXT_AREA1.setBackground(new java.awt.Color(255, 255, 255));
        LOG_TEXT_AREA1.setColumns(20);
        LOG_TEXT_AREA1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        LOG_TEXT_AREA1.setForeground(new java.awt.Color(0, 0, 0));
        LOG_TEXT_AREA1.setRows(5);
        LOG_TEXT_AREA1.setToolTipText("Log program akan muncul di sini");
        LOG_TEXT_AREA1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Penjalanan Program", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UD Digi Kyokasho NP-B", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        LOG_SCROLL_PANE1.setViewportView(LOG_TEXT_AREA1);

        javax.swing.GroupLayout BUKAN_JATAH_PAGELayout = new javax.swing.GroupLayout(BUKAN_JATAH_PAGE);
        BUKAN_JATAH_PAGE.setLayout(BUKAN_JATAH_PAGELayout);
        BUKAN_JATAH_PAGELayout.setHorizontalGroup(
            BUKAN_JATAH_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BUKAN_JATAH_PAGELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE)
                .addContainerGap())
            .addGroup(BUKAN_JATAH_PAGELayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(BUKAN_JATAH_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BUKAN_JATAH_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(INPUT_FILE_PANEL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LOG_SCROLL_PANE1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BUKAN_JATAH_PAGELayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(SUBMIT_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PROSES_DATA_BUKAN_JATAH))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        BUKAN_JATAH_PAGELayout.setVerticalGroup(
            BUKAN_JATAH_PAGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BUKAN_JATAH_PAGELayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(PROSES_DATA_BUKAN_JATAH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(INPUT_FILE_PANEL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(SUBMIT_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LOG_SCROLL_PANE1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE)
                .addContainerGap())
        );

        CARD_TABS.add(BUKAN_JATAH_PAGE, "card4");

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(SIDE_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(CARD_TABS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BACKGROUNDLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(SIDE_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(CARD_TABS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MENGULANG_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENGULANG_BUTTONActionPerformed
        // TODO add your handling code here:
        CARD_TABS.removeAll();
        CARD_TABS.add(MENGULANG_PAGE);
        CARD_TABS.repaint();
        CARD_TABS.revalidate();
    }//GEN-LAST:event_MENGULANG_BUTTONActionPerformed

    private void HOME_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOME_BUTTONActionPerformed
        // TODO add your handling code here:
        CARD_TABS.removeAll();
        CARD_TABS.add(HOME_PAGE);
        CARD_TABS.repaint();
        CARD_TABS.revalidate();
    }//GEN-LAST:event_HOME_BUTTONActionPerformed

    private void BUKAN_JATAH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUKAN_JATAH_BUTTONActionPerformed
        // TODO add your handling code here:
        CARD_TABS.removeAll();
        CARD_TABS.add(BUKAN_JATAH_PAGE);
        CARD_TABS.repaint();
        CARD_TABS.revalidate();
    }//GEN-LAST:event_BUKAN_JATAH_BUTTONActionPerformed

    private void APPLICATION_GUIDE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APPLICATION_GUIDE_BUTTONActionPerformed
        // TODO add your handling code here:
        Desktop BROWSER = Desktop.getDesktop();
        try {
            BROWSER.browse(new URI("https://docs.google.com/document/d/1BZHkr-u6QoEe8U4xQkAYhRDTOId-pFrncAOxQ51s_F4/edit?usp=sharing"));
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, "Link Error", "Warning Message", 0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Link Error", "Warning Message", 0);
        }
    }//GEN-LAST:event_APPLICATION_GUIDE_BUTTONActionPerformed

    private void EXCEL_GUIDE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCEL_GUIDE_BUTTONActionPerformed
        // TODO add your handling code here:
        Desktop BROWSER = Desktop.getDesktop();
        try {
            BROWSER.browse(new URI("https://docs.google.com/document/d/1i4rJ8bh1S1wEotG9jZRVuC2_2qIK0FKbOVyNsQNO8gA/edit?usp=sharing"));
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, "Link Error", "Warning Message", 0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Link Error", "Warning Message", 0);
        }
    }//GEN-LAST:event_EXCEL_GUIDE_BUTTONActionPerformed

    private void SETTINGS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SETTINGS_BUTTONActionPerformed
        // TODO add your handling code here:
        CARD_TABS.removeAll();
        CARD_TABS.add(SETTINGS_PAGE);
        CARD_TABS.repaint();
        CARD_TABS.revalidate();
    }//GEN-LAST:event_SETTINGS_BUTTONActionPerformed

    private void FORM_INPUT_FILE_BROWSE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORM_INPUT_FILE_BROWSE_BUTTONActionPerformed
        // TODO add your handling code here:
        JFileChooser FILE_CHOOSER = new JFileChooser();
        FILE_CHOOSER.showOpenDialog(FILE_CHOOSER);
        File FORM_FILE = FILE_CHOOSER.getSelectedFile();
        String FORM_FILE_PATH = FORM_FILE.getAbsolutePath();
        FORM_INPUT_PATH_FIELD.setForeground(new Color(0, 0, 0));
        FORM_INPUT_PATH_FIELD.setText(FORM_FILE_PATH);
    }//GEN-LAST:event_FORM_INPUT_FILE_BROWSE_BUTTONActionPerformed

    private void DETAILS_INPUT_FILE_BROWSE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETAILS_INPUT_FILE_BROWSE_BUTTONActionPerformed
        // TODO add your handling code here:
        JFileChooser FILE_CHOOSER = new JFileChooser();
        FILE_CHOOSER.showOpenDialog(FILE_CHOOSER);
        File DETAILS_FILE = FILE_CHOOSER.getSelectedFile();
        String DETAILS_FILE_PATH = DETAILS_FILE.getAbsolutePath();
        DETAILS_INPUT_PATH_FIELD.setForeground(new Color(0, 0, 0));
        DETAILS_INPUT_PATH_FIELD.setText(DETAILS_FILE_PATH);
    }//GEN-LAST:event_DETAILS_INPUT_FILE_BROWSE_BUTTONActionPerformed

    private void FORM_INPUT_PATH_FIELDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FORM_INPUT_PATH_FIELDFocusGained
        // TODO add your handling code here:
        if (FORM_INPUT_PATH_FIELD.getText().equals("Masukkan path file...")) {
            FORM_INPUT_PATH_FIELD.setForeground(new Color(0, 0, 0));
            FORM_INPUT_PATH_FIELD.setText("");
        }
    }//GEN-LAST:event_FORM_INPUT_PATH_FIELDFocusGained

    private void FORM_INPUT_PATH_FIELDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FORM_INPUT_PATH_FIELDFocusLost
        // TODO add your handling code here:
        if (FORM_INPUT_PATH_FIELD.getText().equals("")) {
            FORM_INPUT_PATH_FIELD.setForeground(new Color(204, 204, 204));
            FORM_INPUT_PATH_FIELD.setText("Masukkan path file...");
        }
    }//GEN-LAST:event_FORM_INPUT_PATH_FIELDFocusLost

    private void FORM_INPUT_FILE_BROWSE_BUTTON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FORM_INPUT_FILE_BROWSE_BUTTON2ActionPerformed
        // TODO add your handling code here:
        JFileChooser FILE_CHOOSER = new JFileChooser();
        FILE_CHOOSER.showOpenDialog(FILE_CHOOSER);
        File FORM_FILE = FILE_CHOOSER.getSelectedFile();
        String FORM_FILE_PATH = FORM_FILE.getAbsolutePath();
        FORM_INPUT_PATH_FIELD2.setForeground(new Color(0, 0, 0));
        FORM_INPUT_PATH_FIELD2.setText(FORM_FILE_PATH);        
    }//GEN-LAST:event_FORM_INPUT_FILE_BROWSE_BUTTON2ActionPerformed

    private void DETAILS_INPUT_FILE_BROWSE_BUTTON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETAILS_INPUT_FILE_BROWSE_BUTTON2ActionPerformed
        // TODO add your handling code here:
        JFileChooser FILE_CHOOSER = new JFileChooser();
        FILE_CHOOSER.showOpenDialog(FILE_CHOOSER);
        File DETAILS_FILE = FILE_CHOOSER.getSelectedFile();
        String DETAILS_FILE_PATH = DETAILS_FILE.getAbsolutePath();
        DETAILS_INPUT_PATH_FIELD2.setForeground(new Color(0, 0, 0));
        DETAILS_INPUT_PATH_FIELD2.setText(DETAILS_FILE_PATH);        
    }//GEN-LAST:event_DETAILS_INPUT_FILE_BROWSE_BUTTON2ActionPerformed

    private void FORM_INPUT_PATH_FIELD2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FORM_INPUT_PATH_FIELD2FocusGained
        // TODO add your handling code here:
        if (FORM_INPUT_PATH_FIELD2.getText().equals("Masukkan path file...")) {
            FORM_INPUT_PATH_FIELD2.setForeground(new Color(0, 0, 0));
            FORM_INPUT_PATH_FIELD2.setText("");
        }
    }//GEN-LAST:event_FORM_INPUT_PATH_FIELD2FocusGained

    private void FORM_INPUT_PATH_FIELD2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FORM_INPUT_PATH_FIELD2FocusLost
        // TODO add your handling code here:
        if (FORM_INPUT_PATH_FIELD2.getText().equals("")) {
            FORM_INPUT_PATH_FIELD2.setForeground(new Color(204, 204, 204));
            FORM_INPUT_PATH_FIELD2.setText("Masukkan path file...");
        }
    }//GEN-LAST:event_FORM_INPUT_PATH_FIELD2FocusLost

    private void LOGO_IMAGEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGO_IMAGEMouseClicked
        // TODO add your handling code here:
        JFrame IMAGE_FRAME = new JFrame("Sebuah Kenangan Paling Bermakna (SKPB)");
        
        ImageIcon IMAGE = new ImageIcon(FRSGUI.class.getResource("/frs/images/KP 2023-2024.jpeg"));
        
        JLabel LABEL = new JLabel(IMAGE);
        JLabel CAPTION_LABEL = new JLabel("Kenangan KP di SKPB 2023 - 2024.");
        
        CAPTION_LABEL.setHorizontalAlignment(JLabel.CENTER);
        CAPTION_LABEL.setFont(new Font("UD Digi Kyokasho NP-B", 0, 24));
        
        Border VERTICAL_GAP = BorderFactory.createEmptyBorder(10, 0, 10, 0); // Adjust the top and bottom values as needed
        CAPTION_LABEL.setBorder(VERTICAL_GAP);

        CAPTION_LABEL.setForeground(new Color(0, 0, 0));
        
        
        IMAGE_FRAME.getContentPane().setLayout(new BorderLayout());
        IMAGE_FRAME.getContentPane().add(LABEL, BorderLayout.CENTER);
        IMAGE_FRAME.getContentPane().add(CAPTION_LABEL, BorderLayout.SOUTH);
        
        IMAGE_FRAME.pack();
        IMAGE_FRAME.setLocationRelativeTo(null);
        IMAGE_FRAME.setVisible(true);
    }//GEN-LAST:event_LOGO_IMAGEMouseClicked

    private void SAVE_SETTINGS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVE_SETTINGS_BUTTONActionPerformed
        // TODO add your handling code here:
        FRSFORGUI.STUDENT_ID_COLUMN = (int) ID_SPINNER.getValue() - 1;
        FRSFORGUI.RETAKE_COURSE_COLUMN = (int) COURSE_SPINNER.getValue() - 1;
        FRSFORGUI.COURSE_ID_COLUMN = (int) COURSE_ID_SPINNER.getValue() - 1;
        FRSFORGUI.COURSE_CLASS_COLUMN = (int) CLASS_SPINNER.getValue() - 1;
        FRSFORGUI.NUMBER_OF_STUDENTS_COLUMN = (int) NUMBER_OF_STUDENTS_SPINNER.getValue() - 1;
        FRSFORGUI.DEPARTMENTS_COLUMN = (int) DEPARTMENT_SPINNER.getValue() - 1;
        FRSFORGUI.WRITE_CLASS_NUMBER_COLUMN = (int) WRITE_CLASS_NUMBER_SPINNER.getValue() - 1;
        FRSFORGUI.NOTE_COLUMN = (int) NOTE_SPINNER.getValue() - 1;
        FRSFORGUI.COURSE_LIMIT = (int) COURSE_LIMIT_SPINNER.getValue();
        FRSFORGUI.PAUSE_VIEW = (int) DELAY_SPINNER.getValue() * 1000;
    }//GEN-LAST:event_SAVE_SETTINGS_BUTTONActionPerformed

    private void SUBMIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMIT_BUTTONActionPerformed
        // TODO add your handling code here:
        FRSFORGUI.TextArea = LOG_TEXT_AREA;
        try {
            FRSFORGUI.TextArea.append("> Memulai proses memasukkan data mahasiswa ke dalam kelas-kelas.\n");
                    
            // TODO: Working the whole process here
            // TODO: Set path for files
            String INPUT_PATHFILE = FORM_INPUT_PATH_FIELD.getText();
            String CLASS_DETAILS_PATHFILE = DETAILS_INPUT_PATH_FIELD.getText();

            // TODO: Setup the working procedures
            // Step 1: Read the Application From
            java.util.List<FRSFORGUI.Student> STUDENT_LIST = FRSFORGUI.READ_APPLICATION_FORM(INPUT_PATHFILE, 
                    FRSFORGUI.STUDENT_ID_COLUMN, FRSFORGUI.RETAKE_COURSE_COLUMN, FRSFORGUI.COURSE_ID_COLUMN, 
                    FRSFORGUI.COURSE_CLASS_COLUMN, FRSFORGUI.DEPARTMENTS_COLUMN);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);

            // Step 2: Read the Class' Details
            Map<String, Map<String, Map<Integer, Integer>>> AVAILABLE_CLASSES_FOR_DEPARTMENTS_BY_COURSES = FRSFORGUI.READ_CLASS_DETAILS(CLASS_DETAILS_PATHFILE, STUDENT_LIST);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);

            // Step 3: Assign classes for all students
            FRSFORGUI.PROCESS_RESULT MAP_AND_LIST = FRSFORGUI.ASSIGN_CLASS(STUDENT_LIST, AVAILABLE_CLASSES_FOR_DEPARTMENTS_BY_COURSES);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);

            // Step 3.1: Take the map and student list
            AVAILABLE_CLASSES_FOR_DEPARTMENTS_BY_COURSES = MAP_AND_LIST.getUpdatedAvailableClassesForDeparmentsByCourses();
            STUDENT_LIST = MAP_AND_LIST.getUpdatedStudentList();

            // Step 4: Print to Excel
            FRSFORGUI.WRITE_TO_EXCEL(INPUT_PATHFILE, STUDENT_LIST);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);
            
        } catch (IOException e) {
            // TODO: Exception for the main program
            FRSFORGUI.TextArea.append("> Kesalahan saat menyiapkan file input atau output: " + e.getMessage() + "\n");
            e.printStackTrace(pw);
            FRSFORGUI.TextArea.append(sw.toString() + "\n");
        } catch (Exception e) {
            FRSFORGUI.TextArea.append("> Terjadi kesalahan: " + e.getMessage() + "\n");
            e.printStackTrace(pw);
            FRSFORGUI.TextArea.append(sw.toString() + "\n");
        } finally {
            FRSFORGUI.TextArea.append("> Program telah selesai dieksekusi.\n");
        }
    }//GEN-LAST:event_SUBMIT_BUTTONActionPerformed

    private void SUBMIT_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMIT_BUTTON1ActionPerformed
        // TODO add your handling code here:
        FRSFORGUI.TextArea = LOG_TEXT_AREA1;
        try {
            FRSFORGUI.TextArea.append("> Memulai proses memasukkan data mahasiswa ke dalam kelas-kelas.\n");
                    
            // TODO: Working the whole process here
            // TODO: Set path for files
            String INPUT_PATHFILE = FORM_INPUT_PATH_FIELD.getText();
            String CLASS_DETAILS_PATHFILE = DETAILS_INPUT_PATH_FIELD.getText();

            // TODO: Setup the working procedures
            // Step 1: Read the Application From
            java.util.List<FRSFORGUI.Student> STUDENT_LIST = FRSFORGUI.READ_APPLICATION_FORM(INPUT_PATHFILE, 
                    FRSFORGUI.STUDENT_ID_COLUMN, FRSFORGUI.RETAKE_COURSE_COLUMN, FRSFORGUI.COURSE_ID_COLUMN, 
                    FRSFORGUI.COURSE_CLASS_COLUMN, FRSFORGUI.DEPARTMENTS_COLUMN);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);

            // Step 2: Read the Class' Details
            Map<String, Map<String, Map<Integer, Integer>>> AVAILABLE_CLASSES_FOR_DEPARTMENTS_BY_COURSES = FRSFORGUI.READ_CLASS_DETAILS(CLASS_DETAILS_PATHFILE, STUDENT_LIST);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);

            // Step 3: Assign classes for all students
            FRSFORGUI.PROCESS_RESULT MAP_AND_LIST = FRSFORGUI.ASSIGN_CLASS(STUDENT_LIST, AVAILABLE_CLASSES_FOR_DEPARTMENTS_BY_COURSES);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);

            // Step 3.1: Take the map and student list
            AVAILABLE_CLASSES_FOR_DEPARTMENTS_BY_COURSES = MAP_AND_LIST.getUpdatedAvailableClassesForDeparmentsByCourses();
            STUDENT_LIST = MAP_AND_LIST.getUpdatedStudentList();

            // Step 4: Print to Excel
            FRSFORGUI.WRITE_TO_EXCEL(INPUT_PATHFILE, STUDENT_LIST);
            
            Thread.sleep(FRSFORGUI.PAUSE_VIEW);
            
        } catch (IOException e) {
            // TODO: Exception for the main program
            FRSFORGUI.TextArea.append("> Kesalahan saat menyiapkan file input atau output: " + e.getMessage() + "\n");
            e.printStackTrace(pw);
            FRSFORGUI.TextArea.append(sw.toString() + "\n");
        } catch (Exception e) {
            FRSFORGUI.TextArea.append("> Terjadi kesalahan: " + e.getMessage() + "\n");
            e.printStackTrace(pw);
            FRSFORGUI.TextArea.append(sw.toString() + "\n");
        } finally {
            FRSFORGUI.TextArea.append("> Program telah selesai dieksekusi.\n");
        }
    }//GEN-LAST:event_SUBMIT_BUTTON1ActionPerformed

    private void DETAILS_INPUT_PATH_FIELD2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DETAILS_INPUT_PATH_FIELD2FocusGained
        // TODO add your handling code here:
        if (DETAILS_INPUT_PATH_FIELD2.getText().equals("Masukkan path file...")) {
            DETAILS_INPUT_PATH_FIELD2.setForeground(new Color(0, 0, 0));
            DETAILS_INPUT_PATH_FIELD2.setText("");
        }
    }//GEN-LAST:event_DETAILS_INPUT_PATH_FIELD2FocusGained

    private void DETAILS_INPUT_PATH_FIELD2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DETAILS_INPUT_PATH_FIELD2FocusLost
        // TODO add your handling code here:
        if (DETAILS_INPUT_PATH_FIELD2.getText().equals("")) {
            DETAILS_INPUT_PATH_FIELD2.setForeground(new Color(204, 204, 204));
            DETAILS_INPUT_PATH_FIELD2.setText("Masukkan path file...");
        }
    }//GEN-LAST:event_DETAILS_INPUT_PATH_FIELD2FocusLost

    private void DETAILS_INPUT_PATH_FIELDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DETAILS_INPUT_PATH_FIELDFocusGained
        // TODO add your handling code here:
        if (DETAILS_INPUT_PATH_FIELD.getText().equals("Masukkan path file...")) {
            DETAILS_INPUT_PATH_FIELD.setForeground(new Color(0, 0, 0));
            DETAILS_INPUT_PATH_FIELD.setText("");
        }
    }//GEN-LAST:event_DETAILS_INPUT_PATH_FIELDFocusGained

    private void DETAILS_INPUT_PATH_FIELDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DETAILS_INPUT_PATH_FIELDFocusLost
        // TODO add your handling code here:
        if (DETAILS_INPUT_PATH_FIELD.getText().equals("")) {
            DETAILS_INPUT_PATH_FIELD.setForeground(new Color(204, 204, 204));
            DETAILS_INPUT_PATH_FIELD.setText("Masukkan path file...");
        }
    }//GEN-LAST:event_DETAILS_INPUT_PATH_FIELDFocusLost

    public void APPEND_TEXT(String text) {
        SUBMIT_BUTTON.addActionListener(e -> LOG_TEXT_AREA.append(text));
        SUBMIT_BUTTON1.addActionListener(e -> LOG_TEXT_AREA1.append(text));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ABOUT_SCROLL;
    private javax.swing.JTextArea ABOUT_TEXT;
    private javax.swing.JButton APPLICATION_GUIDE_BUTTON;
    private javax.swing.JPanel BACKGROUND;
    private javax.swing.JButton BUKAN_JATAH_BUTTON;
    private javax.swing.JPanel BUKAN_JATAH_PAGE;
    private javax.swing.JPanel CARD_TABS;
    private javax.swing.JLabel CLASS_LABEL;
    private javax.swing.JSpinner CLASS_SPINNER;
    private javax.swing.JLabel COPYRIGHT_LABEL_IN_BUKAN_JATAH_PAGE;
    private javax.swing.JLabel COPYRIGHT_LABEL_IN_HOME_PAGE;
    private javax.swing.JLabel COPYRIGHT_LABEL_IN_MENGULANG_PAGE;
    private javax.swing.JLabel COPYRIGHT_LABEL_IN_SETTINGS_PAGE;
    private javax.swing.JLabel COURSE_ID_LABEL;
    private javax.swing.JSpinner COURSE_ID_SPINNER;
    private javax.swing.JLabel COURSE_LABEL;
    private javax.swing.JLabel COURSE_LIMIT_LABEL;
    private javax.swing.JSpinner COURSE_LIMIT_SPINNER;
    private javax.swing.JSpinner COURSE_SPINNER;
    private javax.swing.JLabel DELAY_LABEL;
    private javax.swing.JSpinner DELAY_SPINNER;
    private javax.swing.JLabel DEPARTMENT_LABEL;
    private javax.swing.JSpinner DEPARTMENT_SPINNER;
    private javax.swing.JButton DETAILS_INPUT_FILE_BROWSE_BUTTON;
    private javax.swing.JButton DETAILS_INPUT_FILE_BROWSE_BUTTON2;
    private javax.swing.JLabel DETAILS_INPUT_LABEL;
    private javax.swing.JLabel DETAILS_INPUT_LABEL2;
    private javax.swing.JTextField DETAILS_INPUT_PATH_FIELD;
    private javax.swing.JTextField DETAILS_INPUT_PATH_FIELD2;
    private javax.swing.JPanel DETAILS_SETTINGS_PANEL;
    private javax.swing.JButton EXCEL_GUIDE_BUTTON;
    private javax.swing.JButton FORM_INPUT_FILE_BROWSE_BUTTON;
    private javax.swing.JButton FORM_INPUT_FILE_BROWSE_BUTTON2;
    private javax.swing.JLabel FORM_INPUT_LABEL;
    private javax.swing.JLabel FORM_INPUT_LABEL2;
    private javax.swing.JTextField FORM_INPUT_PATH_FIELD;
    private javax.swing.JTextField FORM_INPUT_PATH_FIELD2;
    private javax.swing.JPanel FORM_SETTINGS_PANEL;
    private javax.swing.JButton HOME_BUTTON;
    private javax.swing.JPanel HOME_PAGE;
    private javax.swing.JLabel ID_LABEL;
    private javax.swing.JSpinner ID_SPINNER;
    private javax.swing.JPanel INPUT_FILE_PANEL;
    private javax.swing.JPanel INPUT_FILE_PANEL2;
    private javax.swing.JLabel LOGO_IMAGE;
    private javax.swing.JScrollPane LOG_SCROLL_PANE;
    private javax.swing.JScrollPane LOG_SCROLL_PANE1;
    private javax.swing.JTextArea LOG_TEXT_AREA;
    private javax.swing.JTextArea LOG_TEXT_AREA1;
    private javax.swing.JButton MENGULANG_BUTTON;
    private javax.swing.JPanel MENGULANG_PAGE;
    private javax.swing.JPanel MISC_SETTINGS_PANEL;
    private javax.swing.JLabel NOTE_LABEL;
    private javax.swing.JSpinner NOTE_SPINNER;
    private javax.swing.JLabel NUMBER_OF_STUDENTS_LABEL;
    private javax.swing.JSpinner NUMBER_OF_STUDENTS_SPINNER;
    private javax.swing.JLabel PROSES_DATA_BUKAN_JATAH;
    private javax.swing.JLabel PROSES_DATA_MENGULANG;
    private javax.swing.JLabel PROSES_DATA_MENGULANG1;
    private javax.swing.JButton SAVE_SETTINGS_BUTTON;
    private javax.swing.JLabel SELAMAT_DATANG;
    private javax.swing.JButton SETTINGS_BUTTON;
    private javax.swing.JPanel SETTINGS_MENU;
    private javax.swing.JPanel SETTINGS_PAGE;
    private javax.swing.JScrollPane SETTINGS_SCROLL_MENU;
    private javax.swing.JPanel SIDE_PANEL;
    private javax.swing.JLabel START_ROW_LABEL;
    private javax.swing.JSpinner START_ROW_SPINNER;
    private javax.swing.JButton SUBMIT_BUTTON;
    private javax.swing.JButton SUBMIT_BUTTON1;
    private javax.swing.JLabel WELCOME;
    private javax.swing.JLabel WRITE_CLASS_NUMBER_LABEL;
    private javax.swing.JSpinner WRITE_CLASS_NUMBER_SPINNER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}